### PR TITLE
Onboard led support

### PR DESCRIPTION
**Pull request by Mitchlol**

### CODE REVIEW

**Review by kgrdnr — APPROVED** [review]
I suggest using
 #define WS2812_ZERO                        (TIM_PERIOD * 0.3) 

#define WS2812_ONE                        (TIM_PERIOD * 0.7)

And increasing BITBUFFER_PAD as needed, I used 1000, but I suspect that's more than necessary. These changes have improved reliability and reduced glitches with different LED strips in my experience.

**Comment by Mitchlol** [comment]
@kgrdnr Good to know. What strips caused issues? My sk2612 worked perfect, till I turned the motor on, then the rear ones glitched out, but I was able to fix that with a 500ohm resistor.

**Comment by kgrdnr** [comment]
I don't actually know the part number beyond it being a 5v variant, I'm guessing an early ws2812, the ws2815 worked better, but still benefited from adjusting the one/zero times, but I didn't go over 220ohm when testing resistors, so it could have been a hardware thing, but I was experiencing glitching on the bench with just one strip hooked up. I noticed that you also set a fixed refresh rate? Is the actual led refresh rate limited or just the updating led state? A fixed refresh rate should help a lot, I increased the padding zeroes as a hack to lower the refresh rate, but that's less than ideal and it's possible that the other adjustments would not have been needed if the refresh rate had a reasonable cap.

**Comment by Mitchlol** [comment]
> I don't actually know the part number beyond it being a 5v variant, I'm guessing an early ws2812, the ws2815 worked better, but still benefited from adjusting the one/zero times, but I didn't go over 220ohm when testing resistors, so it could have been a hardware thing, but I was experiencing glitching on the bench with just one strip hooked up. I noticed that you also set a fixed refresh rate? Is the actual led refresh rate limited or just the updating led state? A fixed refresh rate should help a lot, I increased the padding zeroes as a hack to lower the refresh rate, but that's less than ideal and it's possible that the other adjustments would not have been needed if the refresh rate had a reasonable cap.

I set the update rate to 20hz, I didn't mess with the timers and dma stuff. I just figured there was no need to run it at 800hz, and wanted to to be consistant across loop timings as some folks run 400hz. Also at 800hz you start to run the risk of not having enough time to write a full frame to the led strip before the next loop, especially for longer strips, as the procol is not super high frequency. This way even if the led function did cause some minor delay to the main loop, it would be less significant, probably.

Tho after some experimentation, 20hz does somewhat limit the types of strobe effects you can do. I love me a super fast 6 color strobe that looks solid white to the human eye till you move, but 20hz is not nearly enough to do that 🤷

Everything can be changed in the future 🤘

**Pull request merged**
